### ISSUE TITLE
Typing error in a message

### ISSUE THREAD

**Issue by mlbonniec** [Skylyxx/SkriptDocsGenerator#1]
Hi, just a small mistake in a message. You typed "requried".
https://github.com/Skylyxx/SkriptDocsGenerator/blob/22bc686509bc43d9bcef0fd328a08e45d88f9ebb/src/main/java/fr/skylyxx/docsgenerator/SkriptDocsGenerator.java#L76

**Comment by Skylyxx** [comment]
Hi, thanks ! Fixed in next commit ^^
