### ISSUE TITLE
NPE while generating docs

### ISSUE THREAD

**Issue by ItsTheSky** [Skylyxx/SkriptDocsGenerator#2]
Hi,
As said in the Discord, here's a NPE 😂
the JSON docs is been generated, but **at the end** of each generation (not one addon especifically) there's that error:
![image](https://user-images.githubusercontent.com/50667548/117535414-eb08c180-aff5-11eb-9f70-6bec3cc0542b.png)
Using latest release, so **1.0**

**Comment by Skylyxx** [comment]
Hi, I will take a look as soon as posible.
You said it appear at the end of each generation, but it seems it appear only for Disky (on your screen). Can you be more specific ?
Thanks !

**Comment by Skylyxx** [comment]
Fixed in commit f20ca8f (https://github.com/Skylyxx/SkriptDocsGenerator/actions/runs/832079962)
